# Generated by Django 4.2.3 on 2024-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(blank=True, choices=[('closed', 'closed'), ('ongoing', 'ongoing')], default='ongoing', max_length=50, null=True),
        ),
    ]
