# Generated by Django 4.2.3 on 2024-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_link',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
