# Generated by Django 4.2.3 on 2024-05-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('Affiliate', 'Affiliate'), ('Creator', 'Creator'), ('Customer', 'Customer')], max_length=200, null=True)),
                ('email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('profile_avatar', models.URLField(blank=True, null=True)),
                ('sales_balance', models.PositiveIntegerField(default=0)),
                ('withdrawal_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
