# Generated by Django 4.2.3 on 2024-05-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_affiliatesubscriptionplan_vendorsubscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('affiliate', 'affiliate'), ('vendor', 'vendor'), ('Customer', 'Customer')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliate_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
