# Generated by Django 4.2.3 on 2024-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
