# Generated by Django 4.2.3 on 2024-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatesubscriptionpayment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions'),
        ),
        migrations.AlterField(
            model_name='affiliatesubscriptionpayment',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('starter', 'starter'), ('pro', 'pro'), ('superior', 'superior')], max_length=100, null=True),
        ),
    ]
