# Generated by Django 4.2.3 on 2024-06-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_vendorsubscriptionpayment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vendor_link',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
