# Generated by Django 4.2.3 on 2024-05-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('amount_in_stock', models.PositiveIntegerField(default=0)),
                ('product_type', models.CharField(blank=True, choices=[('ticket', 'ticket'), ('e-book', 'e-book'), ('physical', 'physical'), ('digial', 'digital')], max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_id', models.UUIDField(default=uuid.UUID('d09b3c99-96f8-4c17-b6af-25e7adff3d2c'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
