# Generated by Django 4.2.3 on 2024-05-29 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('3d64e4a9-4ff6-4e21-8147-8ade24a0a8d9')),
        ),
    ]
