# Generated by Django 4.2.3 on 2024-05-29 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('f1de17b4-99bc-4185-9e37-f11579a10d19')),
        ),
    ]
