# Generated by Django 4.2.3 on 2024-06-16 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_in_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('183036ba-59e2-499e-bb46-e0911b7271a7')),
        ),
    ]
