# Generated by Django 4.2.3 on 2024-06-22 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('aecdd598-9322-40c0-86dd-b00ddd2b4a26')),
        ),
    ]
