# Generated by Django 4.2.3 on 2024-06-22 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('6fe5f124-e55d-4301-a62d-98cf1b3baa2f')),
        ),
    ]
