# Generated by Django 4.2.3 on 2024-06-29 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_product_image_2_product_product_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('18ea446f-7b6a-41d7-903b-24f33ac89129')),
        ),
    ]
