# Generated by Django 4.2.3 on 2024-06-29 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('29927ea9-a530-4960-9b66-597b9c00bf51')),
        ),
    ]
