# Generated by Django 4.2.3 on 2024-06-29 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('c94729db-a432-4017-84e4-a1afc236be55')),
        ),
    ]
